services:
  postgres:
    image: postgres:16-alpine
    container_name: lithic-labs-vehicle-bookings-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vehicle-book-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d vehicle-book-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: lithic-labs-vehicle-bookings-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lithic-labs-vehicle-bookings-api
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: vehicle-book-db
      DB_SYNCHRONIZE: "true"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
